import React, { useState } from 'react';
import { Dumbbell, Utensils, Activity, ChevronRight, AlertTriangle } from 'lucide-react';
import { generateFitnessPlan } from '../services/geminiService';

const Fitness: React.FC = () => {
  const [formData, setFormData] = useState({
    age: 18,
    role: 'Batsman',
    height: 175,
    weight: 70,
    goal: 'Increase explosive power for hitting sixes',
    injuries: ''
  });
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    const generatedPlan = await generateFitnessPlan(
        formData.age,
        formData.role,
        formData.height,
        formData.weight,
        formData.goal,
        formData.injuries
    );
    setPlan(generatedPlan);
    setLoading(false);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="text-center mb-10">
        <h2 className="text-3xl font-extrabold text-white">Elite Performance Lab</h2>
        <p className="mt-2 text-gray-400 max-w-2xl mx-auto">
          Cricket isn't just skill—it's athletics. Get a custom workout and nutrition strategy generated by our AI engine tailored to your body type and role.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Form Section */}
        <div className="lg:col-span-1">
          <form onSubmit={handleSubmit} className="bg-dark-card p-6 rounded-lg border border-gray-700 shadow-xl">
            <h3 className="text-xl font-bold text-white mb-6 flex items-center">
              <Activity className="w-5 h-5 text-cricket mr-2" />
              Your Stats
            </h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Playing Role</label>
                <select 
                    name="role" 
                    value={formData.role} 
                    onChange={handleChange}
                    className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket focus:border-cricket"
                >
                  <option value="Batsman">Batsman</option>
                  <option value="Fast Bowler">Fast Bowler</option>
                  <option value="Spinner">Spinner</option>
                  <option value="Wicket Keeper">Wicket Keeper</option>
                  <option value="All Rounder">All Rounder</option>
                </select>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Height (cm)</label>
                  <input
                    type="number"
                    name="height"
                    value={formData.height}
                    onChange={handleChange}
                    className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket"
                  />
                </div>
                <div>
                    <label className="block text-sm font-medium text-gray-400 mb-1">Weight (kg)</label>
                    <input
                      type="number"
                      name="weight"
                      value={formData.weight}
                      onChange={handleChange}
                      className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket"
                    />
                </div>
              </div>
              
              <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Age</label>
                  <input
                    type="number"
                    name="age"
                    value={formData.age}
                    onChange={handleChange}
                    className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket"
                  />
                </div>

              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Primary Goal</label>
                <input
                    type="text"
                    name="goal"
                    value={formData.goal}
                    onChange={handleChange}
                    placeholder="e.g. Increase pace, better stamina"
                    className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-400 mb-1">Injuries (Optional)</label>
                <textarea
                    name="injuries"
                    value={formData.injuries}
                    onChange={handleChange}
                    rows={2}
                    placeholder="e.g. Lower back pain, ankle sprain"
                    className="w-full bg-gray-800 border border-gray-600 rounded-md p-2 text-white focus:ring-1 focus:ring-cricket"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading}
              className={`mt-6 w-full py-3 rounded-lg font-bold text-white flex items-center justify-center transition-all ${
                loading ? 'bg-gray-600 cursor-wait' : 'bg-gradient-to-r from-cricket to-cricket-dark hover:from-cricket-light hover:to-cricket'
              }`}
            >
              {loading ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Generating Plan...
                </>
              ) : (
                <>
                  Generate My Plan <ChevronRight className="w-4 h-4 ml-1" />
                </>
              )}
            </button>
          </form>
        </div>

        {/* Results Section */}
        <div className="lg:col-span-2">
          {!plan ? (
            <div className="h-full flex flex-col items-center justify-center bg-dark-card/50 rounded-lg border-2 border-dashed border-gray-700 p-12 text-center">
              <div className="bg-gray-800 p-4 rounded-full mb-4">
                <Dumbbell className="w-8 h-8 text-gray-500" />
              </div>
              <h3 className="text-xl font-medium text-white">No Plan Generated Yet</h3>
              <p className="text-gray-400 mt-2">Fill out your profile on the left to get your professional cricket fitness roadmap.</p>
            </div>
          ) : (
            <div className="bg-dark-card rounded-lg border border-gray-700 shadow-xl overflow-hidden animate-fade-in">
              <div className="bg-gray-800 p-4 border-b border-gray-700 flex justify-between items-center">
                 <h3 className="text-lg font-bold text-white flex items-center">
                    <Utensils className="w-5 h-5 text-cricket mr-2" />
                    Your Personalized Roadmap
                 </h3>
                 <span className="text-xs bg-cricket/20 text-cricket px-2 py-1 rounded border border-cricket/30">AI Generated</span>
              </div>
              <div className="p-6 overflow-y-auto max-h-[800px] scrollbar-thin scrollbar-thumb-gray-600 scrollbar-track-gray-800">
                <div className="prose prose-invert max-w-none">
                    <div className="whitespace-pre-wrap font-light text-gray-200">
                        {plan}
                    </div>
                </div>
                
                <div className="mt-8 p-4 bg-yellow-900/20 border border-yellow-700/50 rounded-lg flex items-start">
                    <AlertTriangle className="w-5 h-5 text-yellow-500 mr-3 flex-shrink-0 mt-0.5" />
                    <p className="text-sm text-yellow-200/80">
                        Disclaimer: This is an AI-generated suggestion. Always consult with a qualified coach or physician before starting a new intense training regime.
                    </p>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Fitness;